name: Test Pull Request

on:
  pull_request:
    branches:
      - main

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  check:
    name: Run checks for GutenTAG on ubuntu with python 3.9
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.1.1
        with:
          use-mamba: true
          auto-update-conda: true
          python-version: "3.9"
          channels: defaults
      - name: Install dependencies
        run: |
          pip install ".[dev]"
      - name: Typcheck with mypy
        run: |
          python setup.py typecheck
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

  test:
    name: Test GutenTAG on ${{ matrix.os }} with python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macOS-latest]
        python_version: ["3.9", "3.13"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3.1.1
      with:
        use-mamba: true
        auto-update-conda: true
        python-version: ${{ matrix.python_version }}
        channels: defaults
    - name: Install dependencies
      run: |
        pip install ".[dev]"
    - name: Test with pytest
      run: |
        python setup.py test
    - name: Upload Coverage to Codecov
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage.xml
        flags: unittests
